# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- checkout: self
  clean: true

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'IROSReal'
    organization: 'iros'
    scannerMode: 'MSBuild'
    projectKey: 'SonarCloudWorking'
    extraProperties: |
      sonar.exclusions=**/lib/**
      sonar.cs.opencover.reportsPaths=$(Build.ArtifactStagingDirectory)/coverage/*

- script: dotnet build --configuration $(buildConfiguration)
  workingDirectory: OnlineService
  displayName: 'dotnet build $(buildConfiguration)'
# ...
# do this after other tasks such as building
- task: DotNetCoreCLI@2
  displayName: 'Testing of Business Logic'
  inputs:
    command: test
    projects: 'OnlineService/OnlineService.Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)
    /p:CollectCoverage=true
    /p:CoverletOutputFormat=opencover
    /p:CoverletOutput=$(Build.ArtifactStagingDirectory)/coverage/
    /p:Exclude="[xunit*]*'

- task: SonarCloudAnalyze@1
  continueOnError: true

- task: SonarCloudPublish@1
  continueOnError: true

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'